version: "3.6"


services:
  db:
    image: postgres:14
    ports:
      - "9662:5432"
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=qwerty
    restart: always
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
